/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,jsx}',
    './components/**/*.{js,jsx}',
    './hooks/**/*.{js,jsx}',
    './lib/**/*.{js,jsx}',
  ],
  theme: {
    extend: {
      colors: {
        navy: {
          DEFAULT: '#032D57',
          light: '#0A4278',
          dark: '#021E3A',
          50: '#E6EEF7',
          100: '#C5D8E8',
          200: '#9BBDD8',
          300: '#6EA0C6',
          400: '#4A83B2',
          500: '#032D57',
          600: '#02254A',
          700: '#021E3A',
          800: '#01162B',
          900: '#000D1B',
        },
        brand: { DEFAULT: 'var(--color-primary)', light: 'var(--color-primary)', dark: 'var(--color-primary-strong)' },
        amber: {
          DEFAULT: '#EA921F',
          light: '#F2A94B',
          dark: '#C97A10',
          50: '#FEF5E7',
          100: '#FDEACF',
          200: '#FAD09A',
          300: '#F5B55A',
          400: '#F2A94B',
          500: '#EA921F',
          600: '#C97A10',
          700: '#A6640C',
          800: '#834E09',
          900: '#5C3606',
        },
        sky: {
          DEFAULT: '#C5D8E8',
          light: '#E0ECF5',
          dark: '#9BBDD8',
        },
        slate: {
          DEFAULT: '#38444B',
          light: '#5A6875',
          dark: '#252E34',
          50: '#F0F3F5',
          100: '#D8DFE4',
          200: '#B5C0C8',
          300: '#8D9DA7',
          400: '#677885',
          500: '#38444B',
          600: '#2C353B',
          700: '#20282D',
          800: '#141A1E',
          900: '#080B0D',
        },
        ink: 'var(--color-text)',
        muted: 'var(--color-text-muted)',
        warn: 'var(--color-destructive)',
        primary: 'var(--color-primary)',
        'primary-strong': 'var(--color-primary-strong)',
        'primary-contrast': 'var(--color-primary-contrast)',
        accent: 'var(--color-accent)',
        'accent-contrast': 'var(--color-accent-contrast)',
        canvas: 'var(--color-background)',
        surface: 'var(--color-surface)',
        foreground: 'var(--color-text)',
        secondary: 'var(--color-text-muted)',
        line: 'var(--color-border)',
        success: 'var(--color-success)',
        'success-contrast': 'var(--color-success-contrast)',
        warning: 'var(--color-warning)',
        destructive: 'var(--color-destructive)',
        'info-surface': 'var(--color-info-surface)',
        'info-line': 'var(--color-info-border)',
        'success-surface': 'var(--color-success-surface)',
        'success-line': 'var(--color-success-border)',
        'warning-surface': 'var(--color-warning-surface)',
        'warning-line': 'var(--color-warning-border)',
        'destructive-surface': 'var(--color-destructive-surface)',
        'destructive-line': 'var(--color-destructive-border)',
        subdued: 'var(--color-subdued-surface)',
      },
      fontFamily: {
        sans: ['var(--font-sans)', 'sans-serif'],
        display: ['var(--font-sans)', 'sans-serif'],
        mono: ['var(--font-mono)', 'monospace'],
      },
      fontSize: {
        '2xs': ['0.65rem', { lineHeight: '1rem' }],
      },
      fontWeight: {
        thin: '100',
        extralight: '200',
        light: '300',
        normal: '400',
        medium: '500',
        semibold: '600',
        bold: '700',
        extrabold: '800',
        black: '900',
      },
      boxShadow: {
        menu: 'var(--shadow-menu)',
        dialog: 'var(--shadow-dialog)',
      },
      borderRadius: {
        control: 'var(--radius-control)',
        surface: 'var(--radius-surface)',
      },
    },
  },
  plugins: [],
}
